name: Format terraform files

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: dflook/terraform-fmt@v1
      - uses: EndBug/add-and-commit@v9
        with:
          message: Workflow fix
          committer_name: actions
          committer_email: actions@github.com
